### ISSUE TITLE
unused imports

### ISSUE THREAD

**Issue by markstur** [IBM/watson-document-classifier#1]
based on a quick look, I see unused imports.  python-keystoneclient and some of the nltk things for example.  Also I don't see stemmer and lemmatizer in use.  Not if they somehow impact POS as a side-effect, but the unused vars is odd to see in python.

Maybe I missed something, but it'd be nice to run this through pep8 or something to make sure unused imports and vars are cleaned up.

**Comment by balajikadambi** [comment]
Done. removed the unused imports.

**Comment by stevemar** [comment]
Removed in commit 67022be2452db9694e153626fce3469113b99446
