### ISSUE TITLE
create NLU image should show 'Create' box

### ISSUE THREAD

**Issue by scottdangelo** [IBM/watson-document-classifier#10]
Please take a new screenshot of the window where you create the NLU image. It should show the screen where you are about to create the service, and include the `Create` button.

Replace this:
https://github.com/IBM/watson-document-classifier/raw/master/doc/source/images/bluemix_service_nlu.png

with something similar to this:
![image](https://user-images.githubusercontent.com/14651388/29096226-34022de0-7c51-11e7-8367-beb3f878cfc0.png)

**Comment by balajikadambi** [comment]
Changed the image to include "Create" button

**Comment by stevemar** [comment]
Fixed in 99f9e44bd770a0fbfab0c5d04e594d456fcd0048
