### ISSUE TITLE
update image and instructions for Data Science Experience 'create notebook'

### ISSUE THREAD

**Issue by scottdangelo** [IBM/watson-document-classifier#11]
Unfortunately, the UI for DSX has changed, and the process for creating the notebook looks different.
Please update the image and instructions.
This is no longer valid:
```Use the menu on the left to select My Projects and then Default Project. Click on Add notebooks (upper right) to create a notebook.```

See https://github.com/IBM/pixiedust-traffic-analysis#2-create-the-notebook  
for an example of the new method.

**Comment by balajikadambi** [comment]
I dont see any change in the DSX UI. We have provided instruction to use the "Default Project". The other journey has an additional instruction to create a new project.

**Comment by scottdangelo** [comment]
A new user will see the following:
![image](https://user-images.githubusercontent.com/14651388/29126803-90628e50-7cdc-11e7-9a3a-4e57fdf083ad.png)

I *think* there used to be a menu on the left, as your instructions indicate. I don't see one now.
The menu bar is now on top, at least in my browser. It is called "Projects" now, although previously it may have been on the left and labeled "My projects".

**Comment by balajikadambi** [comment]
Updated the instructions to say 'Projects'. Please see if this suffices.
