### ISSUE TITLE
Please add inputs and outputs  to "Analyzing the results"

### ISSUE THREAD

**Issue by scottdangelo** [IBM/watson-document-classifier#13]
For good examples, please see:
https://github.com/IBM/pixiedust-traffic-analysis#4-analyze-the-results

Since the Analysis of the Notebook results is really the most important part of the journey, please provide details examples of the inputs, how the are annotated/tagged, and the outputs.
We are especially interested in engaging developers who may want to modify the config and and more stages to the configuration json, so please provide brief examples to assist developers in understanding how to do that.

**Comment by balajikadambi** [comment]
The configuration json structure is the input. Once the journey code is run, the user can analyze to see how the classification was done based on the input.
