### ISSUE TITLE
cleanup repo

### ISSUE THREAD

**Issue by scottdangelo** [IBM/watson-document-classifier#19]
We have been cleaning up our repositories in light of changes, and to take care of technical debt.
Please have a look at these items, and apply as needed to this repo.
Please create a Pull Request for these changes.

README (Sign-up name in checklist below)
Replace "Bluemix" with "IBM Cloud"
Change "Journey" to "Code Pattern"
Ensure there are steps after "Flow"
Cleanup old READMEs to align with new template
Double check links section syncs up with IBMCode site
Add blog ? No
Add video?  Yup
Remove "With Watson" blocks
Add "Learn More" sections: https://gist.github.com/dolph/8d5f1c34eb6f46f275563dbe9abdef14

Template for Code Pattern Readme:
https://github.ibm.com/developer-journeys/journey-docs/blob/master/_content/resources/templates/readme_template.md

Example commit:
https://github.com/IBM/watson-conversation-slots-intro/commit/f406290db07d2b180b52408344129cecb64faa84

**Comment by stevemar** [comment]
this looks mostly resolved
