### ISSUE TITLE
### comments style

### ISSUE THREAD

**Issue by markstur** [IBM/watson-document-classifier#2]
The ### comments are a bit loud. It isn't in markdown but in the code.  Python comments describing functions should look like:
def func(self):
    """This is a python function."""

and with additional param docs and return value docs when appropriate to have more than a one-liner (when not obvious).  There are some good examples in the watson python SDK and also here https://github.com/IBM/watson-online-store/blob/master/watsononlinestore/watson_online_store.py

**Comment by balajikadambi** [comment]
Changed the comments style.

**Comment by stevemar** [comment]
Removed in commit 67022be2452db9694e153626fce3469113b99446
