### ISSUE TITLE
Many errors when running classify text step

### ISSUE THREAD

**Issue by DecisionSystems** [IBM/watson-document-classifier#27]
I've been working with this notebook and I seem to be having problems with the step:

Classify the text
response = classify_text(text, config)

The errors that are being thrown are many including TypeError - the text is not JSON serializable.
It's probably me, since I'm a newbie at this. Please check this out to see if it still works.
Thanks much.

**Comment by balajikadambi** [comment]
@DecisionSystems It is because the notebook was built using Python v2.7. I have upgraded the notebook to support Python v3.5. Could you try now.

**Comment by balajikadambi** [comment]
@DecisionSystems  Closing the issue. Please re-open if required.
