### ISSUE TITLE
'DetailedResponse' object is not subscriptable

### ISSUE THREAD

**Issue by jtmhom88** [IBM/watson-document-classifier#30]
I am trying to run the base example notebook. I believe that I got the credentials and set up working.
However, here is where it bugs out:
At step [21]
# Classify the text
response = classify_text(text, config)

Stage - Performing Base Tagging:
    Step - keywords:
      Passion:science
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-5ed05878f222> in <module>()
      1 # Classify the text
----> 2 response = classify_text(text, config)

<ipython-input-19-2192534c627d> in classify_text(text, config)
     87                         if(wordtag != 'UNKNOWN'):
     88                             print('      '+keyword['tag']+':'+wordtag)
---> 89                             augument_NLUResponse(responsejson,'entities',wordtag,keyword['tag'])
     90             elif(steps['type'] == 'd_regex'):
     91                 for regex in steps['d_regex']:

<ipython-input-19-2192534c627d> in augument_NLUResponse(responsejson, updateType, text, tag)
     59             responsejson['keywords'].append({"text":text,"relevance":0.5})
     60     else:
---> 61         if not any(d.get('text', None) == text for d in responsejson['entities']):
     62             responsejson['entities'].append({"type":tag,"text":text,"relevance":0.5,"count":1})
     63 

TypeError: 'DetailedResponse' object is not subscriptable

**Comment by scottdangelo** [comment]
Yes, there was a breaking change in the watson-developer-cloud SDK. I'll be adding a patch to pin the version to 1.5 for now, then we'll fix the code for the new 2.0 version later.
Expect a fix in a few minutes.
