### ISSUE TITLE
'DetailedResponse' object is not subscriptable

### ISSUE THREAD

**Issue by jtmhom88** [IBM/watson-document-classifier#32]
I reloaded the notebook, and I am still getting the same error:
'DetailedResponse' object is not subscriptable

I have done upgrades but to no avail:
!pip install --upgrade watson-developer-cloud
!pip install --upgrade nltk
!pip install --upgrade ibm-cos-sdk

Is there something I'm missing?

**Comment by stevemar** [comment]
This is likely due to the new major revision for the watson SDK, we'll need to make some changes to the code to handle this, but in the mean time we can install v1.5 explicitly.

**Comment by stevemar** [comment]
@jtmhom88 can you try pulling from master or using the latest version of the notebook? the fix to https://github.com/IBM/watson-document-classifier/issues/30 should be in.

**Comment by markstur** [comment]
FYI - The fix there is currently just to pin the version to 1.5 with this one command:

!pip install watson-developer-cloud==1.5

**Comment by jtmhom88** [comment]
OK. I created a new notebook and I see the line:
!pip install watson-developer-cloud==1.5
Seems to work fine now.
Thanks!

**Comment by stevemar** [comment]
Thanks for confirming
