### ISSUE TITLE
add MAINTAINERS, CONTRIBUTING docs

### ISSUE THREAD

**Issue by stevemar** [IBM/watson-document-classifier#8]
See https://github.com/IBM/watson-online-store for an easy copy and paste job

**Comment by balajikadambi** [comment]
Added.

**Comment by stevemar** [comment]
Added in commit 4087bcadb569aa5c56cc9485fe9c4918f791365e and d0a8bd8b0b16e88cfaa0e6adad20861943e2a5ae
