### ISSUE TITLE
add Deploy to Bluemix button.

### ISSUE THREAD

**Issue by scottdangelo** [IBM/watson-document-classifier#9]
imbed this at the top of the Readme:
![Bluemix Deployments](https://deployment-tracker.mybluemix.net/stats/8cbdd782337103af2cd09faf13a2481b/badge.svg)

(that uuid `8cbdd...` will be changed after this merges and the `Deploy to Bluemix` is used. See below)

imbed this in the Readme at the beginning of the `Steps`:

[![Deploy to Bluemix](https://deployment-tracker.mybluemix.net/stats/8cbdd782337103af2cd09faf13a2481b/button.svg)](https://bluemix.net/deploy?repository=https://github.com/IBM/watson-document-classifier)

(that uuid `8cbdd...` will be changed after this merges and the `Deploy to Bluemix` is used. See below)

The Instructions in the `Steps` section will need to be modified.

The `Privacy` part must be added.

The deployment tracker id UUID will need to be modified. This can be found here AFTER the changes are merged and `Deploy to Bluemix` is used:
https://deployment-tracker.mybluemix.net/stats
Look for `watson-document-classifier` and copy the UUID:
![image](https://user-images.githubusercontent.com/14651388/29095914-d9c9567e-7c4f-11e7-8765-8493cd0578c5.png)

See other journeys for an example (i.e.  https://github.com/IBM/watson-conversation-slots-intro )

**Comment by balajikadambi** [comment]
There is no Bluemix deployment in this journey. It uses DSX and Bluemix services - Watson NLU and Object Storage which need to manually created.

**Comment by stevemar** [comment]
I'm of the opinion that the deploy to bluemix button doesn't make sense when it comes to notebooks. We had it for our first few notebooks, and we wired it up to automatically create services (but not deploy an app). We had mixed feedback about that, so I'm willing to let this one slide.
